---
abstract: 'Unsafe signal handlers made convenient'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Signal-Unsafe
provides:
  Signal::Unsafe:
    file: lib/Signal/Unsafe.pm
    version: '0.002'
requires:
  IPC::Signal: '0'
  List::Util: '0'
  POSIX: '0'
  XSLoader: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Signal-Unsafe
  repository: git://github.com/Leont/signal-unsafe.git
version: '0.002'
